/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otopark_otomasyon;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Enes ŞAHİNER
 */
public class hesap_ekrani extends javax.swing.JFrame {

    /**
     * Creates new form hesap_ekrani
     */
    public hesap_ekrani(String plaka_al) {
        initComponents();
        
        try{ 
            SimpleDateFormat bicim3=new SimpleDateFormat("kk.mm");
            GregorianCalendar gcalender=new GregorianCalendar();
            
            txt_plaka.setText(plaka_al);
            String sure=txt_sure.getText();
            String ucret=txt_ucret.getText();
            String saati=bicim3.format(gcalender.getTime());
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/otopark?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();
           
            rs = st.executeQuery("select * from araclar where plaka='"+plaka_al+"'");
            rs.next();
             
            //Float.parseFloat(bicim3.format(gcalender.getTime()).substring(0,4)
            float giris_Saati = Float.parseFloat(rs.getString("saati"));
            float sistem_saati = Float.parseFloat(bicim3.format(gcalender.getTime()).substring(0,4));
            
            if(giris_Saati <= sistem_saati){
                
                float saati_farki =  sistem_saati - giris_Saati;
                float toplam_ucret = Integer.parseInt(rs.getString("ucret")) * saati_farki;
                String degisken = String.valueOf(toplam_ucret);

                txt_sure.setText(String.valueOf(saati_farki));
                txt_ucret.setText(String.valueOf(degisken.substring(0,4)) + " TL");
            }
            else{
               
                float saati_farki =  giris_Saati - sistem_saati;
                
                //JOptionPane.showMessageDialog(null,saati_farki);
                float toplam_ucret = Integer.parseInt(rs.getString("ucret")) * saati_farki;
                String degisken = String.valueOf(toplam_ucret);
                //String sure1 = String.valueOf(saati_farki);

                txt_sure.setText(String.valueOf(saati_farki));
                txt_ucret.setText(String.valueOf(degisken.substring(0,4)) + " TL");
               
                
            }
            
            
            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());    
        }
        
    }

    private hesap_ekrani() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_sure = new javax.swing.JTextField();
        txt_ucret = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_plaka = new javax.swing.JTextField();
        arac_ara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jButton2.setText("ÇIKIŞ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Geçen Süre");

        jLabel3.setText("Ücret");

        jButton1.setText("Araç Çıkışı Yap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Araç Sorgula");

        arac_ara.setText("ARA");
        arac_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arac_araActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_ucret, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(txt_sure, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_plaka, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(arac_ara)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ucret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_plaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(arac_ara)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arac_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arac_araActionPerformed
        
        
        
        
    }//GEN-LAST:event_arac_araActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{
            
            SimpleDateFormat bicim3=new SimpleDateFormat("kk.mm");
            GregorianCalendar gcalender=new GregorianCalendar();
            
            String plaka=txt_plaka.getText();
            String sure=txt_sure.getText();
            String ucret=txt_ucret.getText();
            String saati=bicim3.format(gcalender.getTime());
            //float sistem_saati = Float.parseFloat(saati);
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st, st2 = null;
            ResultSet rs, rs2 = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/otopark?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();
            st2 = con.createStatement();

            rs2 = st2.executeQuery("select * from araclar where plaka='"+plaka+"'");
            rs2.next();
            
            
            float giris_Saati = Float.parseFloat(rs2.getString("saati"));
            float sistem_saati = Float.parseFloat(bicim3.format(gcalender.getTime()).substring(0,4));
            
            if(giris_Saati <= sistem_saati){
                
                float saati_farki =  sistem_saati - giris_Saati;
                float toplam_ucret = Integer.parseInt(rs2.getString("ucret")) * saati_farki;
                String degisken = String.valueOf(toplam_ucret);

                txt_sure.setText(String.valueOf(saati_farki));
                txt_ucret.setText(String.valueOf(degisken.substring(0,3)) + " TL");
                
                String sql1 = "update araclar set giris_cikis='0',toplam_ucret='"+degisken+"' where plaka='"+plaka+"'";
                st.executeUpdate(sql1);

                JOptionPane.showMessageDialog(this, plaka + " - Plakalı Aracın Çıkışı Yapılmıştır.");
            }
            else{
                
                float saati_farki =  giris_Saati - sistem_saati;
                float toplam_ucret = Float.parseFloat(rs2.getString("ucret")) * saati_farki;
                String degisken = String.valueOf(toplam_ucret);
                String sure1 = String.valueOf(saati_farki);

                String sql1 = "update araclar set giris_cikis='0',toplam_ucret='"+toplam_ucret+"' where plaka='"+plaka+"'";
                st.executeUpdate(sql1);

                JOptionPane.showMessageDialog(this, plaka + " - Plakalı Aracın Çıkışı Yapılmıştır.");
            }
             
             
            
        } catch (ClassNotFoundException ex) {
            
        } catch (SQLException ex) {
            
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hesap_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hesap_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hesap_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hesap_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hesap_ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arac_ara;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_plaka;
    private javax.swing.JTextField txt_sure;
    private javax.swing.JTextField txt_ucret;
    // End of variables declaration//GEN-END:variables
}
