/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otopark_otomasyon;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Enes ŞAHİNER
 */
public class unuttum extends javax.swing.JFrame {

    /**
     * Creates new form unuttum
     */
    public unuttum() {
        initComponents();
        
        
        
        txt_email.setBackground(new Color(0,0,0,0));
        txt_email.setBorder(null);
        
        btn_sifre_goster.setBackground(new Color(0,0,0,0));
        btn_sifre_goster.setBorder(null);
        
        txt_email.setOpaque(false);
        btn_sifre_goster.setContentAreaFilled(false);
        btn_cıkıs.setContentAreaFilled(false);
        btn_cıkıs.setFocusable(false);
        
        btn_cıkıs.setBackground(Color.RED);
        btn_cıkıs.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cıkıs = new javax.swing.JButton();
        txt_email = new javax.swing.JTextField();
        btn_sifre_goster = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(595, 440));
        getContentPane().setLayout(null);

        btn_cıkıs.setBackground(new java.awt.Color(0, 51, 204));
        btn_cıkıs.setText("ÇIKIŞ");
        btn_cıkıs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cıkısActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cıkıs);
        btn_cıkıs.setBounds(479, 10, 70, 23);
        getContentPane().add(txt_email);
        txt_email.setBounds(120, 80, 320, 50);

        btn_sifre_goster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sifre_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sifre_gosterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sifre_goster);
        btn_sifre_goster.setBounds(110, 150, 360, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/sifremi_unutum.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 561, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sifre_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sifre_gosterActionPerformed
        
        try{
                                 
            String email=txt_email.getText();
            
            if (email.equals("")) {
                JOptionPane.showMessageDialog(this, "Boş Alanları Doldurunuz.");
            } else {            
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = null;
                Statement st = null;
                ResultSet rs = null;
                
                con = DriverManager.getConnection("jdbc:mysql://localhost/otopark?useUnicode=true&characterEncoding=UTF-8", "root", "");
                st = con.createStatement();
                
                rs = st.executeQuery("select * from uyeler where email='"+email+"'");
                
                if(rs.next()){
                    
                    JOptionPane.showMessageDialog(null, "Şifreniz: "+rs.getString("parola"));
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "Böyle bir E-Posta Kayıtlı Değil!");
                }
                
            }
            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());    
        }
        
    }//GEN-LAST:event_btn_sifre_gosterActionPerformed

    private void btn_cıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cıkısActionPerformed
        uye_giris ac = new uye_giris();
        ac.setVisible(false);
        dispose();
    }//GEN-LAST:event_btn_cıkısActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(unuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(unuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(unuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(unuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new unuttum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cıkıs;
    private javax.swing.JButton btn_sifre_goster;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables
}
