/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otopark_otomasyon;

import java.awt.Color;
import java.io.PrintStream;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Enes ŞAHİNER
 */
public class uye_ekle extends javax.swing.JFrame {

    /**
     * Creates new form uye_ekle
     */
    public uye_ekle(String unvani) {
        JFrame a = new JFrame();
        a.setBackground(Color.yellow);
        
        initComponents();
        
        txt_kadi.setBackground(new Color(0,0,0,0));
        txt_kadi.setBorder(null);

        txt_parola.setBackground(new Color(0,0,0,0));
        txt_parola.setBorder(null);

        btn_cikis.setBackground(new Color(0,0,0,0));
        btn_cikis.setBorder(null);

        btn_ekle.setBackground(new Color(0,0,0,0));
        btn_ekle.setBorder(null);

        txt_unvan.setBackground(new Color(0,0,0,0));
        txt_unvan.setBorder(null);

        txt_email.setBackground(new Color(0,0,0,0));
        txt_email.setBorder(null);

        txt_kadi.setOpaque(false);
        txt_parola.setOpaque(false);
        btn_cikis.setContentAreaFilled(false);
        btn_ekle.setContentAreaFilled(false);
        txt_unvan.setOpaque(false);
        txt_email.setOpaque(false);
        
       
            
        if(unvani.equals("Müdür"))
        {
            txt_unvan.setVisible(true);
        }
        else if(unvani.equals("Müşteri")){
            txt_unvan.setVisible(false);
        }
         

    }

    private uye_ekle() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cikis = new javax.swing.JButton();
        txt_kadi = new javax.swing.JTextField();
        txt_parola = new javax.swing.JPasswordField();
        txt_email = new javax.swing.JTextField();
        txt_unvan = new javax.swing.JTextField();
        btn_ekle = new javax.swing.JButton();
        resim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(560, 600));
        setPreferredSize(new java.awt.Dimension(560, 600));
        getContentPane().setLayout(null);

        btn_cikis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cikis);
        btn_cikis.setBounds(500, 10, 40, 40);
        getContentPane().add(txt_kadi);
        txt_kadi.setBounds(100, 70, 350, 50);
        getContentPane().add(txt_parola);
        txt_parola.setBounds(100, 160, 350, 50);
        getContentPane().add(txt_email);
        txt_email.setBounds(100, 250, 350, 50);
        getContentPane().add(txt_unvan);
        txt_unvan.setBounds(100, 340, 350, 40);

        btn_ekle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ekle);
        btn_ekle.setBounds(90, 420, 360, 50);

        resim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/uye_ol.jpg"))); // NOI18N
        resim.setMinimumSize(new java.awt.Dimension(550, 548));
        resim.setPreferredSize(new java.awt.Dimension(550, 548));
        getContentPane().add(resim);
        resim.setBounds(0, 0, 540, 548);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        
        try{

            String kadi=txt_kadi.getText();
            String parola=txt_parola.getText();
            String email=txt_email.getText();
            String unvan=txt_unvan.getText();
            
            if (kadi.equals("") || parola.equals("") || email.equals("")) {
                JOptionPane.showMessageDialog(this, "Boş Alanları Doldurunuz.");
            } else {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = null;
                Statement st = null;
                ResultSet rs = null;

                con = DriverManager.getConnection("jdbc:mysql://localhost/otopark?useUnicode=true&characterEncoding=UTF-8", "root", "");
                st = con.createStatement();

                String sql = "INSERT INTO uyeler (kadi,parola,email,unvan)"
                + " VALUES ('"+kadi+"', '"+parola+"', '"+email+"', '"+unvan+"')";
                
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, " "+ kadi + " Adlı Kullanıcı Eklenmiştir.");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }

    }//GEN-LAST:event_btn_ekleActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        
        this.setVisible(false);
        dispose();
        
    }//GEN-LAST:event_btn_cikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uye_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uye_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uye_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uye_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uye_ekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_ekle;
    private javax.swing.JLabel resim;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_kadi;
    private javax.swing.JPasswordField txt_parola;
    private javax.swing.JTextField txt_unvan;
    // End of variables declaration//GEN-END:variables
}
